export const contentAgentConfig = {
  siteUrl: 'https://fleetbase.io',
  defaultCountry: 'us',
  scheduleDescription: 'Weekly, Monday UTC',
  maxAhrefsRowsPerRequest: 100,
  maxShortlistedTopics: 5,
  maxDraftsPerRun: 1,
  requireExplicitDraftCreation: true,
  featureImage: {
    enabledByDefault: true,
    model: 'gpt-image-1.5',
    size: '1536x1024',
    quality: 'auto',
    outputFormat: 'png',
    styleGuide:
      'Create clean editorial logistics software imagery. Use abstract dashboards, delivery routes, warehouse or fleet operations, and modern supply-chain UI motifs. Avoid text, logos, brand marks, distorted UI labels, people close-ups, and generic stock-photo compositions.',
  },
  contentStrategy: {
    defaultFocusByUtcDay: {
      1: 'logistics-software',
      3: 'fleetbase-api-tutorial',
      5: 'supply-chain-software',
    },
    allowedFocuses: [
      'logistics-software',
      'supply-chain-software',
      'fleetbase-api-tutorial',
    ],
    requiredRelevance:
      'Topics must be specific to Fleetbase, logistics software, fleet operations, delivery management, supply chain operations, warehouse/inventory workflows, or building logistics workflows with the Fleetbase API.',
    contentMix:
      'Use Monday runs for logistics software SEO, Wednesday runs for Fleetbase API/tutorial articles, and Friday runs for supply chain or inventory software SEO.',
    tutorialExamples: [
      'build a delivery tracking workflow with the Fleetbase API',
      'create proof of delivery workflows with Fleetbase',
      'connect Fleetbase webhooks to an order management system',
      'build a dispatch dashboard with Fleetbase APIs',
      'set up route planning and driver assignment in Fleetbase',
    ],
  },
  ahrefs: {
    apiBaseUrl: 'https://api.ahrefs.com/v3',
    keywordEndpoint: '/keywords-explorer/matching-terms',
    keywordSelectFields: [
      'keyword',
      'volume',
      'difficulty',
      'traffic_potential',
      'parent_topic',
      'intents',
    ],
  },
  seedClusters: [
    'open source fleet management',
    'open source logistics software',
    'fleet management software',
    'dispatch management software',
    'delivery management software',
    'last mile delivery software',
    'transport management software',
    'supply chain management software',
    'warehouse inventory software',
    'proof of delivery software',
    'route optimization API',
    'delivery management API',
    'fleet management API',
    'proof of delivery',
    'logistics API',
    'dispatch API',
    'delivery tracking API',
    'webhook tutorial',
    'fleet management API tutorial',
    'logistics API tutorial',
    'delivery API tutorial',
  ],
  competitorDomains: [
    'onfleet.com',
    'route4me.com',
    'bringg.com',
    'shipday.com',
    'track-pod.com',
    'samsara.com',
  ],
  context: {
    maxSelectedFiles: 24,
    maxCharsPerFile: 1800,
    budgets: {
      scoring: {
        maxSelectedFiles: 12,
        maxCharsPerSource: 900,
        maxTotalChars: 12000,
      },
      drafting: {
        maxSelectedFiles: 18,
        maxCharsPerSource: 1200,
        maxTotalChars: 18000,
      },
    },
    includeGlobs: [
      'src/app/**/page.tsx',
      'src/app/**/*page-content.tsx',
      'content/docs/**/*.mdx',
      'README.md',
    ],
    excludePathParts: [
      'node_modules',
      '.next',
      '.source',
      'vendor/postman',
      'public/',
    ],
  },
  sourceTruthRepos: [
    {
      repo: 'fleetbase/core-api',
      path: 'source-truth/core-api',
      category: 'backend-api',
      includeGlobs: [
        'routes/**/*.php',
        'src/Http/Controllers/**/*.php',
        'src/Http/Requests/**/*.php',
        'src/Http/Resources/**/*.php',
        'src/Models/**/*.php',
        'src/Policies/**/*.php',
        'src/Services/**/*.php',
        'README.md',
        'docs/**/*.md',
      ],
    },
    {
      repo: 'fleetbase/fleetops',
      path: 'source-truth/fleetops',
      category: 'fleetops',
      includeGlobs: [
        'addon/**/*.{js,ts,hbs}',
        'app/**/*.{js,ts,hbs}',
        'server/**/*.{php,js,ts}',
        'README.md',
        'docs/**/*.md',
      ],
    },
    {
      repo: 'fleetbase/ledger',
      path: 'source-truth/ledger',
      category: 'ledger',
      includeGlobs: [
        'addon/**/*.{js,ts,hbs}',
        'app/**/*.{js,ts,hbs}',
        'server/**/*.{php,js,ts}',
        'src/**/*.{php,js,ts}',
        'README.md',
        'docs/**/*.md',
      ],
    },
    {
      repo: 'fleetbase/storefront',
      path: 'source-truth/storefront',
      category: 'storefront',
      includeGlobs: [
        'addon/**/*.{js,ts,hbs}',
        'app/**/*.{js,ts,hbs}',
        'server/**/*.{php,js,ts}',
        'src/**/*.{php,js,ts}',
        'README.md',
        'docs/**/*.md',
      ],
    },
    {
      repo: 'fleetbase/dev-engine',
      path: 'source-truth/dev-engine',
      category: 'developer-platform',
      includeGlobs: [
        'addon/**/*.{js,ts,hbs}',
        'app/**/*.{js,ts,hbs}',
        'server/**/*.{php,js,ts}',
        'src/**/*.{php,js,ts}',
        'README.md',
        'docs/**/*.md',
      ],
    },
    {
      repo: 'fleetbase/iam-engine',
      path: 'source-truth/iam-engine',
      category: 'identity-access',
      includeGlobs: [
        'addon/**/*.{js,ts,hbs}',
        'app/**/*.{js,ts,hbs}',
        'server/**/*.{php,js,ts}',
        'src/**/*.{php,js,ts}',
        'README.md',
        'docs/**/*.md',
      ],
    },
    {
      repo: 'fleetbase/ember-core',
      path: 'source-truth/ember-core',
      category: 'frontend-core',
      includeGlobs: [
        'addon/**/*.{js,ts,hbs}',
        'app/**/*.{js,ts,hbs}',
        'src/**/*.{js,ts,hbs}',
        'README.md',
        'docs/**/*.md',
      ],
    },
    {
      repo: 'fleetbase/pallet',
      path: 'source-truth/pallet',
      category: 'pallet',
      includeGlobs: [
        'addon/**/*.{js,ts,hbs}',
        'app/**/*.{js,ts,hbs}',
        'server/**/*.{php,js,ts}',
        'src/**/*.{php,js,ts}',
        'README.md',
        'docs/**/*.md',
      ],
    },
  ],
  ghost: {
    apiVersion: 'v5.0',
    internalTags: ['#ai-generated', '#needs-review', '#seo-content-agent'],
  },
};
